# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogList(object):
    def setupUi(self, DialogList):
        DialogList.setObjectName("DialogList")
        DialogList.resize(400, 600)
        DialogList.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.tableView = QtWidgets.QTableView(DialogList)
        self.tableView.setGeometry(QtCore.QRect(20, 90, 361, 401))
        self.tableView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableView.setStyleSheet("QTableView {\n"
"background-color: rgb(60, 60, 60);\n"
"border: 1px solid rgb(255,255,255);\n"
"border-radius: 15px;\n"
"gridline-color: rgb(60, 60, 60);\n"
"selection-background-color: rgb(100, 100, 100);\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(60, 60, 60);\n"
"color:white;\n"
"padding: 5px;\n"
"font: 25 18pt \"Futura PT Light\";\n"
"height: 40px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QTableView::item{\n"
"border-style: none;\n"
"border-bottom: rgb(255,255,255);\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"color: yellow;\n"
"}")
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setProperty("showDropIndicator", False)
        self.tableView.setShowGrid(False)
        self.tableView.setWordWrap(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(False)
        self.tableView.horizontalHeader().setDefaultSectionSize(180)
        self.tableView.horizontalHeader().setHighlightSections(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.labelTodayRegs = QtWidgets.QLabel(DialogList)
        self.labelTodayRegs.setGeometry(QtCore.QRect(30, 20, 291, 51))
        self.labelTodayRegs.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 25pt \"Futura PT Demi\";")
        self.labelTodayRegs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTodayRegs.setObjectName("labelTodayRegs")
        self.buttonDEL = QtWidgets.QPushButton(DialogList)
        self.buttonDEL.setGeometry(QtCore.QRect(20, 510, 361, 71))
        self.buttonDEL.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonDEL.setObjectName("buttonDEL")

        self.retranslateUi(DialogList)
        QtCore.QMetaObject.connectSlotsByName(DialogList)

    def retranslateUi(self, DialogList):
        _translate = QtCore.QCoreApplication.translate
        DialogList.setWindowTitle(_translate("DialogList", "LIST"))
        self.labelTodayRegs.setText(_translate("DialogList", "Today regs:"))
        self.buttonDEL.setText(_translate("DialogList", "DELETE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogList = QtWidgets.QDialog()
    ui = Ui_DialogList()
    ui.setupUi(DialogList)
    DialogList.show()
    sys.exit(app.exec_())
