# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogList(object):
    def setupUi(self, DialogList):
        DialogList.setObjectName("DialogList")
        DialogList.resize(400, 600)
        DialogList.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.tableView = QtWidgets.QTableView(DialogList)
        self.tableView.setGeometry(QtCore.QRect(20, 110, 361, 192))
        self.tableView.setStyleSheet("QTableView {\n"
"background-color: rgb(60, 60, 60);\n"
"border: 1px solid rgb(255,255,255);\n"
"border-bottom-right-radius: 15px;\n"
"border-bottom-left-radius: 15px;\n"
"}\n"
"\n"
"QTableView::section{\n"
"background-color: rgb(60, 60, 60);\n"
"color:white;\n"
"border: 1px solid rgb(255,255,255);\n"
"height:50px;\n"
"font: 25 14pt \"Futura PT Light\";\n"
"}\n"
"\n"
"QTableView::item{\n"
"border-style: none;\n"
"border-bottom: rgb(255,255,255);\n"
"}\n"
"\n"
"QTableView::item::selected {\n"
"border: none;\n"
"\n"
"}")
        self.tableView.setObjectName("tableView")

        self.retranslateUi(DialogList)
        QtCore.QMetaObject.connectSlotsByName(DialogList)

    def retranslateUi(self, DialogList):
        _translate = QtCore.QCoreApplication.translate
        DialogList.setWindowTitle(_translate("DialogList", "LIST"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogList = QtWidgets.QDialog()
    ui = Ui_DialogList()
    ui.setupUi(DialogList)
    DialogList.show()
    sys.exit(app.exec_())
