# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSettings(object):
    def setupUi(self, DialogSettings):
        DialogSettings.setObjectName("DialogSettings")
        DialogSettings.resize(392, 300)
        DialogSettings.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.labelSettings = QtWidgets.QLabel(DialogSettings)
        self.labelSettings.setGeometry(QtCore.QRect(20, 20, 121, 41))
        self.labelSettings.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 20pt \"Futura PT Demi\";")
        self.labelSettings.setObjectName("labelSettings")
        self.labelEverydayGoal = QtWidgets.QLabel(DialogSettings)
        self.labelEverydayGoal.setGeometry(QtCore.QRect(20, 90, 141, 41))
        self.labelEverydayGoal.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 17pt \"Futura PT Light\";")
        self.labelEverydayGoal.setObjectName("labelEverydayGoal")
        self.labelDaysInGraph = QtWidgets.QLabel(DialogSettings)
        self.labelDaysInGraph.setGeometry(QtCore.QRect(20, 160, 141, 41))
        self.labelDaysInGraph.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 17pt \"Futura PT Light\";")
        self.labelDaysInGraph.setObjectName("labelDaysInGraph")
        self.buttonSAVE = QtWidgets.QPushButton(DialogSettings)
        self.buttonSAVE.setGeometry(QtCore.QRect(10, 240, 371, 51))
        self.buttonSAVE.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonSAVE.setObjectName("buttonSAVE")
        self.lineEditDaysInGraph = QtWidgets.QLineEdit(DialogSettings)
        self.lineEditDaysInGraph.setGeometry(QtCore.QRect(160, 157, 71, 51))
        self.lineEditDaysInGraph.setStyleSheet("font: 57 22pt \"Futura PT Demi\";\n"
"color: white;\n"
"border: 1px solid rgb(255,255,255);\n"
"border-radius:15px;")
        self.lineEditDaysInGraph.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditDaysInGraph.setObjectName("lineEditDaysInGraph")
        self.framePickTime = QtWidgets.QFrame(DialogSettings)
        self.framePickTime.setGeometry(QtCore.QRect(160, 80, 201, 61))
        self.framePickTime.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.framePickTime.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePickTime.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePickTime.setObjectName("framePickTime")
        self.labelH = QtWidgets.QLabel(self.framePickTime)
        self.labelH.setGeometry(QtCore.QRect(50, 16, 31, 31))
        self.labelH.setStyleSheet("border: none;\n"
"font: 57 22pt \"Futura PT Demi\";\n"
"color: white;")
        self.labelH.setAlignment(QtCore.Qt.AlignCenter)
        self.labelH.setObjectName("labelH")
        self.labelMIN = QtWidgets.QLabel(self.framePickTime)
        self.labelMIN.setGeometry(QtCore.QRect(123, 16, 61, 31))
        self.labelMIN.setStyleSheet("border: none;\n"
"font: 57 22pt \"Futura PT Demi\";\n"
"color: white;")
        self.labelMIN.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMIN.setObjectName("labelMIN")
        self.lineEditHours = QtWidgets.QLineEdit(self.framePickTime)
        self.lineEditHours.setGeometry(QtCore.QRect(10, 15, 41, 31))
        self.lineEditHours.setStyleSheet("border: none;\n"
"font: 57 22pt \"Futura PT Demi\";\n"
"color: white;border: none;")
        self.lineEditHours.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditHours.setObjectName("lineEditHours")
        self.lineEditMinutes = QtWidgets.QLineEdit(self.framePickTime)
        self.lineEditMinutes.setGeometry(QtCore.QRect(80, 15, 41, 31))
        self.lineEditMinutes.setStyleSheet("font: 57 22pt \"Futura PT Demi\";\n"
"color: white;\n"
"border: none;")
        self.lineEditMinutes.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditMinutes.setObjectName("lineEditMinutes")

        self.retranslateUi(DialogSettings)
        QtCore.QMetaObject.connectSlotsByName(DialogSettings)

    def retranslateUi(self, DialogSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogSettings.setWindowTitle(_translate("DialogSettings", "SETTINGS"))
        self.labelSettings.setText(_translate("DialogSettings", "Settings"))
        self.labelEverydayGoal.setText(_translate("DialogSettings", "Everyday goal:"))
        self.labelDaysInGraph.setText(_translate("DialogSettings", "Days in graph:"))
        self.buttonSAVE.setText(_translate("DialogSettings", "SAVE"))
        self.lineEditDaysInGraph.setText(_translate("DialogSettings", "0"))
        self.labelH.setText(_translate("DialogSettings", "H"))
        self.labelMIN.setText(_translate("DialogSettings", "MIN"))
        self.lineEditHours.setText(_translate("DialogSettings", "0"))
        self.lineEditMinutes.setText(_translate("DialogSettings", "0"))
# import addTime_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogSettings = QtWidgets.QDialog()
    ui = Ui_DialogSettings()
    ui.setupUi(DialogSettings)
    DialogSettings.show()
    sys.exit(app.exec_())
