# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.centralwidget.setObjectName("centralwidget")

        self.frameToday = QtWidgets.QFrame(self.centralwidget)
        self.frameToday.setGeometry(QtCore.QRect(30, 40, 280, 291))
        self.frameToday.setStyleSheet("background-color: rgb(60, 60, 60);\n"
                                      "border-radius: 15px;\n"
                                      "border: 1px solid rgb(255, 255, 255);")
        self.frameToday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToday.setObjectName("frameToday")
        self.labelToday = QtWidgets.QLabel(self.frameToday)
        self.labelToday.setGeometry(QtCore.QRect(75, 10, 131, 51))
        self.labelToday.setStyleSheet("border: none;\n"
                                      "color: white;\n"
                                      "font: 57 25pt \"Futura PT Demi\";")
        self.labelToday.setAlignment(QtCore.Qt.AlignCenter)
        self.labelToday.setObjectName("labelToday")

        self.clockIcon = QtWidgets.QLabel(self.frameToday)
        self.clockIcon.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.clockIcon.setStyleSheet("border: none;")
        self.clockIcon.setText("")
        self.clockIcon.setPixmap(QtGui.QPixmap(":/icons/schedule30.svg"))
        self.clockIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.clockIcon.setObjectName("clockIcon")

        self.todayWorkTime = QtWidgets.QLabel(self.frameToday)
        self.todayWorkTime.setGeometry(QtCore.QRect(60, 80, 141, 31))
        self.todayWorkTime.setStyleSheet("border: none;\n"
                                         "color: white;\n"
                                         "font: 25 16pt \"Futura PT Light\";")
        self.todayWorkTime.setObjectName("todayWorkTime")

        self.progressIcon = QtWidgets.QLabel(self.frameToday)
        self.progressIcon.setGeometry(QtCore.QRect(20, 120, 31, 31))
        self.progressIcon.setStyleSheet("border: none;")
        self.progressIcon.setText("")
        self.progressIcon.setPixmap(QtGui.QPixmap(":/icons/incomplete31.svg"))
        self.progressIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.progressIcon.setObjectName("progressIcon")

        self.todayProgress = QtWidgets.QLabel(self.frameToday)
        self.todayProgress.setGeometry(QtCore.QRect(60, 120, 111, 31))
        self.todayProgress.setStyleSheet("border: none;\n"
                                         "color: white;\n"
                                         "font: 25 16pt \"Futura PT Light\";")
        self.todayProgress.setObjectName("todayProgress")

        self.finishIcon = QtWidgets.QLabel(self.frameToday)
        self.finishIcon.setGeometry(QtCore.QRect(20, 160, 31, 31))
        self.finishIcon.setStyleSheet("border: none;")
        self.finishIcon.setText("")
        self.finishIcon.setPixmap(QtGui.QPixmap(":/icons/goal.svg"))
        self.finishIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.finishIcon.setObjectName("finishIcon")

        self.todayFinishTime = QtWidgets.QLabel(self.frameToday)
        self.todayFinishTime.setGeometry(QtCore.QRect(60, 158, 141, 31))
        self.todayFinishTime.setStyleSheet("border: none;\n"
                                           "color: white;\n"
                                           "font: 25 16pt \"Futura PT Light\";")
        self.todayFinishTime.setObjectName("todayFinishTime")

        self.buttonADD = QtWidgets.QPushButton(self.frameToday)
        self.buttonADD.setGeometry(QtCore.QRect(15, 210, 120, 61))
        self.buttonADD.setStyleSheet("QPushButton {\n"
                                     "border: 1px solid rgb(255, 255, 255);\n"
                                     "background-color: rgb(70, 70, 70);\n"
                                     "border-radius: 15px;\n"
                                     "font: 57 12pt \"Futura PT Demi\";\n"
                                     "color: white;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "border: 1px solid rgb(255, 255, 255);\n"
                                     "background-color: rgb(90, 90, 90);\n"
                                     "border-radius: 15px;\n"
                                     "font: 57 12pt \"Futura PT Demi\";\n"
                                     "color: white;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "border: 2px solid rgb(255, 255, 255);\n"
                                     "background-color: rgb(90, 90, 90);\n"
                                     "border-radius: 15px;\n"
                                     "font: 57 12pt \"Futura PT Demi\";\n"
                                     "color: white;\n"
                                     "}")
        self.buttonADD.setObjectName("buttonADD")

        self.buttonSTARTTIMER = QtWidgets.QPushButton(self.frameToday)
        self.buttonSTARTTIMER.setGeometry(QtCore.QRect(145, 210, 120, 61))
        self.buttonSTARTTIMER.setStyleSheet("QPushButton {\n"
                                            "border: 1px solid rgb(255, 255, 255);\n"
                                            "background-color: rgb(70, 70, 70);\n"
                                            "border-radius: 15px;\n"
                                            "font: 57 12pt \"Futura PT Demi\";\n"
                                            "color: white;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "border: 1px solid rgb(255, 255, 255);\n"
                                            "background-color: rgb(90, 90, 90);\n"
                                            "border-radius: 15px;\n"
                                            "font: 57 12pt \"Futura PT Demi\";\n"
                                            "color: white;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed {\n"
                                            "border: 2px solid rgb(255, 255, 255);\n"
                                            "background-color: rgb(90, 90, 90);\n"
                                            "border-radius: 15px;\n"
                                            "font: 57 12pt \"Futura PT Demi\";\n"
                                            "color: white;\n"
                                            "}")
        self.buttonSTARTTIMER.setObjectName("buttonSTARTTIMER")\

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TRACKER"))
        self.labelToday.setText(_translate("MainWindow", "TODAY"))
        self.todayWorkTime.setText(_translate("MainWindow", "0 h 00 min"))
        self.todayProgress.setText(_translate("MainWindow", "0%"))
        self.todayFinishTime.setText(_translate("MainWindow", "0 h 00 min"))
        self.buttonADD.setText(_translate("MainWindow", "ADD"))
        self.buttonSTARTTIMER.setText(_translate("MainWindow", "START TIMER"))


from smallDB import db_init

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    db_init()
    MainWindow.show()
    sys.exit(app.exec_())
