# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.centralwidget.setObjectName("centralwidget")
        self.frameToday = QtWidgets.QFrame(self.centralwidget)
        self.frameToday.setGeometry(QtCore.QRect(30, 40, 280, 291))
        self.frameToday.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.frameToday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToday.setObjectName("frameToday")
        self.labelToday = QtWidgets.QLabel(self.frameToday)
        self.labelToday.setGeometry(QtCore.QRect(75, 10, 131, 51))
        self.labelToday.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 22pt \"Futura PT Demi\";")
        self.labelToday.setAlignment(QtCore.Qt.AlignCenter)
        self.labelToday.setObjectName("labelToday")
        self.clockIcon = QtWidgets.QLabel(self.frameToday)
        self.clockIcon.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.clockIcon.setStyleSheet("border: none;")
        self.clockIcon.setText("")
        self.clockIcon.setPixmap(QtGui.QPixmap(":/icons/anotgher_clock30.png"))
        self.clockIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.clockIcon.setObjectName("clockIcon")
        self.todayWorkTime = QtWidgets.QLabel(self.frameToday)
        self.todayWorkTime.setGeometry(QtCore.QRect(60, 80, 141, 31))
        self.todayWorkTime.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.todayWorkTime.setObjectName("todayWorkTime")
        self.progressIcon = QtWidgets.QLabel(self.frameToday)
        self.progressIcon.setGeometry(QtCore.QRect(20, 120, 31, 31))
        self.progressIcon.setStyleSheet("border: none;")
        self.progressIcon.setText("")
        self.progressIcon.setPixmap(QtGui.QPixmap(":/icons/percent30.png"))
        self.progressIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.progressIcon.setObjectName("progressIcon")
        self.todayProgress = QtWidgets.QLabel(self.frameToday)
        self.todayProgress.setGeometry(QtCore.QRect(60, 120, 111, 31))
        self.todayProgress.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.todayProgress.setObjectName("todayProgress")
        self.finishIcon = QtWidgets.QLabel(self.frameToday)
        self.finishIcon.setGeometry(QtCore.QRect(20, 160, 31, 31))
        self.finishIcon.setStyleSheet("border: none;")
        self.finishIcon.setText("")
        self.finishIcon.setPixmap(QtGui.QPixmap(":/icons/finish.png"))
        self.finishIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.finishIcon.setObjectName("finishIcon")
        self.todayFinishTime = QtWidgets.QLabel(self.frameToday)
        self.todayFinishTime.setGeometry(QtCore.QRect(60, 158, 141, 31))
        self.todayFinishTime.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.todayFinishTime.setObjectName("todayFinishTime")
        self.buttonADD = QtWidgets.QPushButton(self.frameToday)
        self.buttonADD.setGeometry(QtCore.QRect(15, 210, 120, 61))
        self.buttonADD.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonADD.setObjectName("buttonADD")
        self.buttonSTARTTIMER = QtWidgets.QPushButton(self.frameToday)
        self.buttonSTARTTIMER.setGeometry(QtCore.QRect(145, 210, 120, 61))
        self.buttonSTARTTIMER.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonSTARTTIMER.setObjectName("buttonSTARTTIMER")
        self.buttonNextDay = QtWidgets.QPushButton(self.frameToday)
        self.buttonNextDay.setGeometry(QtCore.QRect(195, 20, 31, 31))
        self.buttonNextDay.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonNextDay.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/arrow_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonNextDay.setIcon(icon)
        self.buttonNextDay.setIconSize(QtCore.QSize(50, 50))
        self.buttonNextDay.setObjectName("buttonNextDay")
        self.buttonPrevDay = QtWidgets.QPushButton(self.frameToday)
        self.buttonPrevDay.setGeometry(QtCore.QRect(52, 20, 31, 31))
        self.buttonPrevDay.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonPrevDay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/arrow_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPrevDay.setIcon(icon1)
        self.buttonPrevDay.setIconSize(QtCore.QSize(50, 50))
        self.buttonPrevDay.setObjectName("buttonPrevDay")
        self.frameWeek = QtWidgets.QFrame(self.centralwidget)
        self.frameWeek.setGeometry(QtCore.QRect(340, 40, 431, 291))
        self.frameWeek.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.frameWeek.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameWeek.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameWeek.setObjectName("frameWeek")
        self.labelThisWeek = QtWidgets.QLabel(self.frameWeek)
        self.labelThisWeek.setGeometry(QtCore.QRect(75, 10, 291, 51))
        self.labelThisWeek.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 22pt \"Futura PT Demi\";")
        self.labelThisWeek.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThisWeek.setObjectName("labelThisWeek")
        self.IconAverage = QtWidgets.QLabel(self.frameWeek)
        self.IconAverage.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.IconAverage.setStyleSheet("border: none;")
        self.IconAverage.setText("")
        self.IconAverage.setPixmap(QtGui.QPixmap(":/icons/avg30.png"))
        self.IconAverage.setAlignment(QtCore.Qt.AlignCenter)
        self.IconAverage.setObjectName("IconAverage")
        self.labelAverage = QtWidgets.QLabel(self.frameWeek)
        self.labelAverage.setGeometry(QtCore.QRect(60, 80, 71, 31))
        self.labelAverage.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelAverage.setObjectName("labelAverage")
        self.IconOverall = QtWidgets.QLabel(self.frameWeek)
        self.IconOverall.setGeometry(QtCore.QRect(20, 120, 31, 31))
        self.IconOverall.setStyleSheet("border: none;")
        self.IconOverall.setText("")
        self.IconOverall.setPixmap(QtGui.QPixmap(":/icons/clock30.png"))
        self.IconOverall.setAlignment(QtCore.Qt.AlignCenter)
        self.IconOverall.setObjectName("IconOverall")
        self.labelOverall = QtWidgets.QLabel(self.frameWeek)
        self.labelOverall.setGeometry(QtCore.QRect(60, 122, 61, 31))
        self.labelOverall.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelOverall.setObjectName("labelOverall")
        self.IconPercent = QtWidgets.QLabel(self.frameWeek)
        self.IconPercent.setGeometry(QtCore.QRect(20, 160, 31, 31))
        self.IconPercent.setStyleSheet("border: none;")
        self.IconPercent.setText("")
        self.IconPercent.setPixmap(QtGui.QPixmap(":/icons/percent30.png"))
        self.IconPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.IconPercent.setObjectName("IconPercent")
        self.labelPercent = QtWidgets.QLabel(self.frameWeek)
        self.labelPercent.setGeometry(QtCore.QRect(60, 161, 61, 31))
        self.labelPercent.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelPercent.setObjectName("labelPercent")
        self.buttonNextWeek = QtWidgets.QPushButton(self.frameWeek)
        self.buttonNextWeek.setGeometry(QtCore.QRect(303, 20, 31, 31))
        self.buttonNextWeek.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonNextWeek.setText("")
        self.buttonNextWeek.setIcon(icon)
        self.buttonNextWeek.setIconSize(QtCore.QSize(50, 50))
        self.buttonNextWeek.setObjectName("buttonNextWeek")
        self.buttonPrevWeek = QtWidgets.QPushButton(self.frameWeek)
        self.buttonPrevWeek.setGeometry(QtCore.QRect(103, 20, 31, 31))
        self.buttonPrevWeek.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonPrevWeek.setText("")
        self.buttonPrevWeek.setIcon(icon1)
        self.buttonPrevWeek.setIconSize(QtCore.QSize(50, 50))
        self.buttonPrevWeek.setObjectName("buttonPrevWeek")
        self.WeekAverage = QtWidgets.QLabel(self.frameWeek)
        self.WeekAverage.setGeometry(QtCore.QRect(140, 80, 111, 31))
        self.WeekAverage.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekAverage.setObjectName("WeekAverage")
        self.WeekOverall = QtWidgets.QLabel(self.frameWeek)
        self.WeekOverall.setGeometry(QtCore.QRect(140, 122, 111, 31))
        self.WeekOverall.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekOverall.setObjectName("WeekOverall")
        self.WeekPercent = QtWidgets.QLabel(self.frameWeek)
        self.WeekPercent.setGeometry(QtCore.QRect(140, 161, 61, 31))
        self.WeekPercent.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekPercent.setObjectName("WeekPercent")
        self.IconFulldays = QtWidgets.QLabel(self.frameWeek)
        self.IconFulldays.setGeometry(QtCore.QRect(20, 200, 31, 31))
        self.IconFulldays.setStyleSheet("border: none;")
        self.IconFulldays.setText("")
        self.IconFulldays.setPixmap(QtGui.QPixmap(":/icons/finish.png"))
        self.IconFulldays.setAlignment(QtCore.Qt.AlignCenter)
        self.IconFulldays.setObjectName("IconFulldays")
        self.labelFulldays = QtWidgets.QLabel(self.frameWeek)
        self.labelFulldays.setGeometry(QtCore.QRect(60, 200, 81, 31))
        self.labelFulldays.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelFulldays.setObjectName("labelFulldays")
        self.IconGrowth = QtWidgets.QLabel(self.frameWeek)
        self.IconGrowth.setGeometry(QtCore.QRect(20, 240, 31, 31))
        self.IconGrowth.setStyleSheet("border: none;")
        self.IconGrowth.setText("")
        self.IconGrowth.setPixmap(QtGui.QPixmap(":/icons/arrow-up-right-50.png"))
        self.IconGrowth.setAlignment(QtCore.Qt.AlignCenter)
        self.IconGrowth.setObjectName("IconGrowth")
        self.labelGrowth = QtWidgets.QLabel(self.frameWeek)
        self.labelGrowth.setGeometry(QtCore.QRect(60, 238, 81, 31))
        self.labelGrowth.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelGrowth.setObjectName("labelGrowth")
        self.WeekFullDays = QtWidgets.QLabel(self.frameWeek)
        self.WeekFullDays.setGeometry(QtCore.QRect(140, 200, 61, 31))
        self.WeekFullDays.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekFullDays.setObjectName("WeekFullDays")
        self.WeekGrowth = QtWidgets.QLabel(self.frameWeek)
        self.WeekGrowth.setGeometry(QtCore.QRect(140, 240, 200, 31))
        self.WeekGrowth.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekGrowth.setObjectName("WeekGrowth")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TRACKER"))
        self.labelToday.setText(_translate("MainWindow", "TODAY"))
        self.todayWorkTime.setText(_translate("MainWindow", "2 h 37 min"))
        self.todayProgress.setText(_translate("MainWindow", "76%"))
        self.todayFinishTime.setText(_translate("MainWindow", "0 h 23 min"))
        self.buttonADD.setText(_translate("MainWindow", "ADD"))
        self.buttonSTARTTIMER.setText(_translate("MainWindow", "START TIMER"))
        self.labelThisWeek.setText(_translate("MainWindow", "THIS WEEK"))
        self.labelAverage.setText(_translate("MainWindow", "Average:"))
        self.labelOverall.setText(_translate("MainWindow", "Overall:"))
        self.labelPercent.setText(_translate("MainWindow", "Percent:"))
        self.WeekAverage.setText(_translate("MainWindow", "3 h 25 min"))
        self.WeekOverall.setText(_translate("MainWindow", "22 h 43 min"))
        self.WeekPercent.setText(_translate("MainWindow", "78%"))
        self.labelFulldays.setText(_translate("MainWindow", "Full days:"))
        self.labelGrowth.setText(_translate("MainWindow", "Growth:"))
        self.WeekFullDays.setText(_translate("MainWindow", "6 days"))
        self.WeekGrowth.setText(_translate("MainWindow", "11%"))

import mainPage_res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
