# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 600)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(40, 36, 40);")
        self.centralwidget.setObjectName("centralwidget")
        self.frameToday = QtWidgets.QFrame(self.centralwidget)
        self.frameToday.setGeometry(QtCore.QRect(30, 40, 350, 291))
        self.frameToday.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.frameToday.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToday.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToday.setObjectName("frameToday")
        self.labelToday = QtWidgets.QLabel(self.frameToday)
        self.labelToday.setGeometry(QtCore.QRect(113, 10, 131, 51))
        self.labelToday.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 21pt \"Futura PT Demi\";")
        self.labelToday.setAlignment(QtCore.Qt.AlignCenter)
        self.labelToday.setObjectName("labelToday")
        self.clockIcon = QtWidgets.QLabel(self.frameToday)
        self.clockIcon.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.clockIcon.setStyleSheet("border: none;")
        self.clockIcon.setText("")
        self.clockIcon.setPixmap(QtGui.QPixmap(":/icons/anotgher_clock30.png"))
        self.clockIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.clockIcon.setObjectName("clockIcon")
        self.todayWorkTime = QtWidgets.QLabel(self.frameToday)
        self.todayWorkTime.setGeometry(QtCore.QRect(60, 80, 141, 31))
        self.todayWorkTime.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.todayWorkTime.setObjectName("todayWorkTime")
        self.progressIcon = QtWidgets.QLabel(self.frameToday)
        self.progressIcon.setGeometry(QtCore.QRect(20, 120, 31, 31))
        self.progressIcon.setStyleSheet("border: none;")
        self.progressIcon.setText("")
        self.progressIcon.setPixmap(QtGui.QPixmap(":/icons/percent30.png"))
        self.progressIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.progressIcon.setObjectName("progressIcon")
        self.todayProgress = QtWidgets.QLabel(self.frameToday)
        self.todayProgress.setGeometry(QtCore.QRect(60, 120, 111, 31))
        self.todayProgress.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.todayProgress.setObjectName("todayProgress")
        self.finishIcon = QtWidgets.QLabel(self.frameToday)
        self.finishIcon.setGeometry(QtCore.QRect(20, 160, 31, 31))
        self.finishIcon.setStyleSheet("border: none;")
        self.finishIcon.setText("")
        self.finishIcon.setPixmap(QtGui.QPixmap(":/icons/finish.png"))
        self.finishIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.finishIcon.setObjectName("finishIcon")
        self.todayFinishTime = QtWidgets.QLabel(self.frameToday)
        self.todayFinishTime.setGeometry(QtCore.QRect(60, 158, 141, 31))
        self.todayFinishTime.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.todayFinishTime.setObjectName("todayFinishTime")
        self.buttonADD = QtWidgets.QPushButton(self.frameToday)
        self.buttonADD.setGeometry(QtCore.QRect(13, 217, 61, 61))
        self.buttonADD.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonADD.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/plus-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonADD.setIcon(icon)
        self.buttonADD.setIconSize(QtCore.QSize(32, 32))
        self.buttonADD.setObjectName("buttonADD")
        self.buttonNextDay = QtWidgets.QPushButton(self.frameToday)
        self.buttonNextDay.setGeometry(QtCore.QRect(235, 20, 31, 31))
        self.buttonNextDay.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonNextDay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/arrow_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonNextDay.setIcon(icon1)
        self.buttonNextDay.setIconSize(QtCore.QSize(50, 50))
        self.buttonNextDay.setObjectName("buttonNextDay")
        self.buttonPrevDay = QtWidgets.QPushButton(self.frameToday)
        self.buttonPrevDay.setGeometry(QtCore.QRect(90, 20, 31, 31))
        self.buttonPrevDay.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonPrevDay.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/arrow_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPrevDay.setIcon(icon2)
        self.buttonPrevDay.setIconSize(QtCore.QSize(50, 50))
        self.buttonPrevDay.setObjectName("buttonPrevDay")
        self.buttonLIST = QtWidgets.QPushButton(self.frameToday)
        self.buttonLIST.setGeometry(QtCore.QRect(85, 217, 61, 61))
        self.buttonLIST.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonLIST.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/list-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonLIST.setIcon(icon3)
        self.buttonLIST.setIconSize(QtCore.QSize(32, 32))
        self.buttonLIST.setObjectName("buttonLIST")
        self.buttonSETTINGS = QtWidgets.QPushButton(self.frameToday)
        self.buttonSETTINGS.setGeometry(QtCore.QRect(157, 217, 61, 61))
        self.buttonSETTINGS.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonSETTINGS.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/settings40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSETTINGS.setIcon(icon4)
        self.buttonSETTINGS.setIconSize(QtCore.QSize(32, 32))
        self.buttonSETTINGS.setObjectName("buttonSETTINGS")
        self.frameTimer = QtWidgets.QFrame(self.frameToday)
        self.frameTimer.setGeometry(QtCore.QRect(230, 157, 108, 121))
        self.frameTimer.setStyleSheet("background-color: rgb(60, 55, 60);\n"
"")
        self.frameTimer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTimer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTimer.setObjectName("frameTimer")
        self.buttonSTARTTIMER = QtWidgets.QPushButton(self.frameTimer)
        self.buttonSTARTTIMER.setGeometry(QtCore.QRect(10, 10, 88, 51))
        self.buttonSTARTTIMER.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonSTARTTIMER.setObjectName("buttonSTARTTIMER")
        self.buttonPAUSETIMER = QtWidgets.QPushButton(self.frameTimer)
        self.buttonPAUSETIMER.setGeometry(QtCore.QRect(10, 70, 41, 41))
        self.buttonPAUSETIMER.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonPAUSETIMER.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons8-pause-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPAUSETIMER.setIcon(icon5)
        self.buttonPAUSETIMER.setIconSize(QtCore.QSize(25, 25))
        self.buttonPAUSETIMER.setObjectName("buttonPAUSETIMER")
        self.buttonSAVETIMER = QtWidgets.QPushButton(self.frameTimer)
        self.buttonSAVETIMER.setGeometry(QtCore.QRect(57, 70, 41, 41))
        self.buttonSAVETIMER.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 10pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.buttonSAVETIMER.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons8-download-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSAVETIMER.setIcon(icon6)
        self.buttonSAVETIMER.setIconSize(QtCore.QSize(24, 24))
        self.buttonSAVETIMER.setObjectName("buttonSAVETIMER")
        self.frameWeek = QtWidgets.QFrame(self.centralwidget)
        self.frameWeek.setGeometry(QtCore.QRect(410, 40, 361, 291))
        self.frameWeek.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.frameWeek.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameWeek.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameWeek.setObjectName("frameWeek")
        self.labelThisWeek = QtWidgets.QLabel(self.frameWeek)
        self.labelThisWeek.setGeometry(QtCore.QRect(70, 10, 221, 51))
        self.labelThisWeek.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 21pt \"Futura PT Demi\";")
        self.labelThisWeek.setAlignment(QtCore.Qt.AlignCenter)
        self.labelThisWeek.setObjectName("labelThisWeek")
        self.IconAverage = QtWidgets.QLabel(self.frameWeek)
        self.IconAverage.setGeometry(QtCore.QRect(20, 80, 31, 31))
        self.IconAverage.setStyleSheet("border: none;")
        self.IconAverage.setText("")
        self.IconAverage.setPixmap(QtGui.QPixmap(":/icons/avg30.png"))
        self.IconAverage.setAlignment(QtCore.Qt.AlignCenter)
        self.IconAverage.setObjectName("IconAverage")
        self.labelAverage = QtWidgets.QLabel(self.frameWeek)
        self.labelAverage.setGeometry(QtCore.QRect(60, 80, 71, 31))
        self.labelAverage.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelAverage.setObjectName("labelAverage")
        self.IconOverall = QtWidgets.QLabel(self.frameWeek)
        self.IconOverall.setGeometry(QtCore.QRect(20, 120, 31, 31))
        self.IconOverall.setStyleSheet("border: none;")
        self.IconOverall.setText("")
        self.IconOverall.setPixmap(QtGui.QPixmap(":/icons/clock30.png"))
        self.IconOverall.setAlignment(QtCore.Qt.AlignCenter)
        self.IconOverall.setObjectName("IconOverall")
        self.labelOverall = QtWidgets.QLabel(self.frameWeek)
        self.labelOverall.setGeometry(QtCore.QRect(60, 122, 61, 31))
        self.labelOverall.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelOverall.setObjectName("labelOverall")
        self.IconPercent = QtWidgets.QLabel(self.frameWeek)
        self.IconPercent.setGeometry(QtCore.QRect(20, 160, 31, 31))
        self.IconPercent.setStyleSheet("border: none;")
        self.IconPercent.setText("")
        self.IconPercent.setPixmap(QtGui.QPixmap(":/icons/percent30.png"))
        self.IconPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.IconPercent.setObjectName("IconPercent")
        self.labelPercent = QtWidgets.QLabel(self.frameWeek)
        self.labelPercent.setGeometry(QtCore.QRect(60, 161, 61, 31))
        self.labelPercent.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelPercent.setObjectName("labelPercent")
        self.buttonNextWeek = QtWidgets.QPushButton(self.frameWeek)
        self.buttonNextWeek.setGeometry(QtCore.QRect(260, 20, 31, 31))
        self.buttonNextWeek.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonNextWeek.setText("")
        self.buttonNextWeek.setIcon(icon1)
        self.buttonNextWeek.setIconSize(QtCore.QSize(50, 50))
        self.buttonNextWeek.setObjectName("buttonNextWeek")
        self.buttonPrevWeek = QtWidgets.QPushButton(self.frameWeek)
        self.buttonPrevWeek.setGeometry(QtCore.QRect(70, 20, 31, 31))
        self.buttonPrevWeek.setStyleSheet("QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 9px;\n"
"}")
        self.buttonPrevWeek.setText("")
        self.buttonPrevWeek.setIcon(icon2)
        self.buttonPrevWeek.setIconSize(QtCore.QSize(50, 50))
        self.buttonPrevWeek.setObjectName("buttonPrevWeek")
        self.WeekAverage = QtWidgets.QLabel(self.frameWeek)
        self.WeekAverage.setGeometry(QtCore.QRect(140, 80, 111, 31))
        self.WeekAverage.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekAverage.setObjectName("WeekAverage")
        self.WeekOverall = QtWidgets.QLabel(self.frameWeek)
        self.WeekOverall.setGeometry(QtCore.QRect(140, 122, 111, 31))
        self.WeekOverall.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekOverall.setObjectName("WeekOverall")
        self.WeekPercent = QtWidgets.QLabel(self.frameWeek)
        self.WeekPercent.setGeometry(QtCore.QRect(140, 161, 61, 31))
        self.WeekPercent.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekPercent.setObjectName("WeekPercent")
        self.IconFulldays = QtWidgets.QLabel(self.frameWeek)
        self.IconFulldays.setGeometry(QtCore.QRect(20, 200, 31, 31))
        self.IconFulldays.setStyleSheet("border: none;")
        self.IconFulldays.setText("")
        self.IconFulldays.setPixmap(QtGui.QPixmap(":/icons/finish.png"))
        self.IconFulldays.setAlignment(QtCore.Qt.AlignCenter)
        self.IconFulldays.setObjectName("IconFulldays")
        self.labelFulldays = QtWidgets.QLabel(self.frameWeek)
        self.labelFulldays.setGeometry(QtCore.QRect(60, 200, 81, 31))
        self.labelFulldays.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelFulldays.setObjectName("labelFulldays")
        self.IconGrowth = QtWidgets.QLabel(self.frameWeek)
        self.IconGrowth.setGeometry(QtCore.QRect(20, 240, 31, 31))
        self.IconGrowth.setStyleSheet("border: none;")
        self.IconGrowth.setText("")
        self.IconGrowth.setPixmap(QtGui.QPixmap(":/icons/arrow-up-right-50.png"))
        self.IconGrowth.setAlignment(QtCore.Qt.AlignCenter)
        self.IconGrowth.setObjectName("IconGrowth")
        self.labelGrowth = QtWidgets.QLabel(self.frameWeek)
        self.labelGrowth.setGeometry(QtCore.QRect(60, 238, 81, 31))
        self.labelGrowth.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelGrowth.setObjectName("labelGrowth")
        self.WeekFullDays = QtWidgets.QLabel(self.frameWeek)
        self.WeekFullDays.setGeometry(QtCore.QRect(140, 200, 61, 31))
        self.WeekFullDays.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekFullDays.setObjectName("WeekFullDays")
        self.WeekGrowth = QtWidgets.QLabel(self.frameWeek)
        self.WeekGrowth.setGeometry(QtCore.QRect(140, 239, 200, 31))
        self.WeekGrowth.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.WeekGrowth.setObjectName("WeekGrowth")
        self.frameGraphic = QtWidgets.QFrame(self.centralwidget)
        self.frameGraphic.setGeometry(QtCore.QRect(30, 360, 741, 221))
        self.frameGraphic.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.frameGraphic.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGraphic.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGraphic.setObjectName("frameGraphic")
        self.graph = PlotWidget(self.frameGraphic)
        self.graph.setGeometry(QtCore.QRect(10, 10, 721, 201))
        self.graph.setStyleSheet("border: none;")
        self.graph.setObjectName("graph")
        self.frameTop5 = QtWidgets.QFrame(self.centralwidget)
        self.frameTop5.setGeometry(QtCore.QRect(800, 40, 281, 291))
        self.frameTop5.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.frameTop5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTop5.setObjectName("frameTop5")
        self.labelTop5 = QtWidgets.QLabel(self.frameTop5)
        self.labelTop5.setGeometry(QtCore.QRect(110, 10, 111, 51))
        self.labelTop5.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 21pt \"Futura PT Demi\";")
        self.labelTop5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTop5.setObjectName("labelTop5")
        self.IconPedestal = QtWidgets.QLabel(self.frameTop5)
        self.IconPedestal.setGeometry(QtCore.QRect(75, 10, 51, 51))
        self.IconPedestal.setStyleSheet("border: none;")
        self.IconPedestal.setText("")
        self.IconPedestal.setPixmap(QtGui.QPixmap(":/icons/pedestal-50.png"))
        self.IconPedestal.setAlignment(QtCore.Qt.AlignCenter)
        self.IconPedestal.setObjectName("IconPedestal")
        self.label1 = QtWidgets.QLabel(self.frameTop5)
        self.label1.setGeometry(QtCore.QRect(20, 80, 21, 31))
        self.label1.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.frameTop5)
        self.label2.setGeometry(QtCore.QRect(20, 122, 21, 31))
        self.label2.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.frameTop5)
        self.label3.setGeometry(QtCore.QRect(20, 161, 21, 31))
        self.label3.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.frameTop5)
        self.label4.setGeometry(QtCore.QRect(20, 200, 21, 31))
        self.label4.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.frameTop5)
        self.label5.setGeometry(QtCore.QRect(20, 238, 21, 31))
        self.label5.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.label5.setObjectName("label5")
        self.labelPlace1 = QtWidgets.QLabel(self.frameTop5)
        self.labelPlace1.setGeometry(QtCore.QRect(40, 80, 231, 31))
        self.labelPlace1.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelPlace1.setObjectName("labelPlace1")
        self.labelPlace2 = QtWidgets.QLabel(self.frameTop5)
        self.labelPlace2.setGeometry(QtCore.QRect(40, 122, 231, 31))
        self.labelPlace2.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelPlace2.setObjectName("labelPlace2")
        self.labelPlace3 = QtWidgets.QLabel(self.frameTop5)
        self.labelPlace3.setGeometry(QtCore.QRect(40, 161, 231, 31))
        self.labelPlace3.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelPlace3.setObjectName("labelPlace3")
        self.labelPlace4 = QtWidgets.QLabel(self.frameTop5)
        self.labelPlace4.setGeometry(QtCore.QRect(40, 200, 231, 31))
        self.labelPlace4.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelPlace4.setObjectName("labelPlace4")
        self.labelPlace5 = QtWidgets.QLabel(self.frameTop5)
        self.labelPlace5.setGeometry(QtCore.QRect(40, 238, 231, 31))
        self.labelPlace5.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 16pt \"Futura PT Light\";")
        self.labelPlace5.setObjectName("labelPlace5")
        self.frameFind = QtWidgets.QFrame(self.centralwidget)
        self.frameFind.setGeometry(QtCore.QRect(800, 360, 281, 221))
        self.frameFind.setStyleSheet("background-color: rgb(60, 60, 60);\n"
"border-radius: 15px;\n"
"border: 1px solid rgb(255, 255, 255);")
        self.frameFind.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFind.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFind.setObjectName("frameFind")
        self.labelFind = QtWidgets.QLabel(self.frameFind)
        self.labelFind.setGeometry(QtCore.QRect(110, 10, 111, 51))
        self.labelFind.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 57 21pt \"Futura PT Demi\";")
        self.labelFind.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFind.setObjectName("labelFind")
        self.IconFind = QtWidgets.QLabel(self.frameFind)
        self.IconFind.setGeometry(QtCore.QRect(75, 10, 51, 51))
        self.IconFind.setStyleSheet("border: none;")
        self.IconFind.setText("")
        self.IconFind.setPixmap(QtGui.QPixmap(":/icons/find-50.png"))
        self.IconFind.setAlignment(QtCore.Qt.AlignCenter)
        self.IconFind.setObjectName("IconFind")
        self.findLineEdit = QtWidgets.QLineEdit(self.frameFind)
        self.findLineEdit.setGeometry(QtCore.QRect(20, 80, 191, 41))
        self.findLineEdit.setStyleSheet("background-color: rgb(60, 55, 60);\n"
"font: 12pt \"Futura PT Book\";\n"
"color:white;")
        self.findLineEdit.setObjectName("findLineEdit")
        self.pushButtonFIND = QtWidgets.QPushButton(self.frameFind)
        self.pushButtonFIND.setGeometry(QtCore.QRect(220, 80, 41, 41))
        self.pushButtonFIND.setStyleSheet("QPushButton {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 1px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border: 2px solid rgb(255, 255, 255);\n"
"background-color: rgb(90, 90, 90);\n"
"border-radius: 15px;\n"
"font: 57 12pt \"Futura PT Demi\";\n"
"color: white;\n"
"}")
        self.pushButtonFIND.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/find-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFIND.setIcon(icon7)
        self.pushButtonFIND.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonFIND.setObjectName("pushButtonFIND")
        self.labelTime = QtWidgets.QLabel(self.frameFind)
        self.labelTime.setGeometry(QtCore.QRect(65, 146, 61, 31))
        self.labelTime.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 20pt \"Futura PT Light\";")
        self.labelTime.setObjectName("labelTime")
        self.IconOverall_2 = QtWidgets.QLabel(self.frameFind)
        self.IconOverall_2.setGeometry(QtCore.QRect(20, 140, 41, 41))
        self.IconOverall_2.setStyleSheet("border: none;")
        self.IconOverall_2.setText("")
        self.IconOverall_2.setPixmap(QtGui.QPixmap(":/icons/clock30.png"))
        self.IconOverall_2.setAlignment(QtCore.Qt.AlignCenter)
        self.IconOverall_2.setObjectName("IconOverall_2")
        self.labelTimedata = QtWidgets.QLabel(self.frameFind)
        self.labelTimedata.setGeometry(QtCore.QRect(130, 146, 121, 31))
        self.labelTimedata.setStyleSheet("border: none;\n"
"color: white;\n"
"font: 25 20pt \"Futura PT Light\";")
        self.labelTimedata.setObjectName("labelTimedata")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TRACKER"))
        self.labelToday.setText(_translate("MainWindow", "TODAY"))
        self.todayWorkTime.setText(_translate("MainWindow", "2 h 37 min"))
        self.todayProgress.setText(_translate("MainWindow", "76%"))
        self.todayFinishTime.setText(_translate("MainWindow", "0 h 23 min"))
        self.buttonSTARTTIMER.setText(_translate("MainWindow", "START TIMER"))
        self.labelThisWeek.setText(_translate("MainWindow", "THIS WEEK"))
        self.labelAverage.setText(_translate("MainWindow", "Average:"))
        self.labelOverall.setText(_translate("MainWindow", "Overall:"))
        self.labelPercent.setText(_translate("MainWindow", "Percent:"))
        self.WeekAverage.setText(_translate("MainWindow", "3 h 25 min"))
        self.WeekOverall.setText(_translate("MainWindow", "22 h 43 min"))
        self.WeekPercent.setText(_translate("MainWindow", "78%"))
        self.labelFulldays.setText(_translate("MainWindow", "Full days:"))
        self.labelGrowth.setText(_translate("MainWindow", "Growth:"))
        self.WeekFullDays.setText(_translate("MainWindow", "6 days"))
        self.WeekGrowth.setText(_translate("MainWindow", "11%"))
        self.labelTop5.setText(_translate("MainWindow", "TOP 5"))
        self.label1.setText(_translate("MainWindow", "1."))
        self.label2.setText(_translate("MainWindow", "2."))
        self.label3.setText(_translate("MainWindow", "3."))
        self.label4.setText(_translate("MainWindow", "4."))
        self.label5.setText(_translate("MainWindow", "5."))
        self.labelPlace1.setText(_translate("MainWindow", "Task 1"))
        self.labelPlace2.setText(_translate("MainWindow", "Task 2"))
        self.labelPlace3.setText(_translate("MainWindow", "Task 3"))
        self.labelPlace4.setText(_translate("MainWindow", "Task 4"))
        self.labelPlace5.setText(_translate("MainWindow", "Task 5"))
        self.labelFind.setText(_translate("MainWindow", "FIND"))
        self.labelTime.setText(_translate("MainWindow", "Time:"))
        self.labelTimedata.setText(_translate("MainWindow", "0 h 00 min"))
from pyqtgraph import PlotWidget
import mainPage_res


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
